version: "3.3"
services: 
 nginx:
  image: nginx
  ports:
   - "80:80"
  links:
   - indexation_1
  volumes: 
   - "./nginx/conf.d/:/etc/nginx/conf.d"
 mysql:
  image: mysql
  environment:
   MYSQL_DATABASE: test
   MYSQL_ROOT_PASSWORD: root
   MYSQL_ROOT_HOST: '%'
  ports:
   - "3306:3306"
  restart: always
 indexation_1: 
  image: pegasusma/indexation:0-SNAPSHOT
  depends_on:
   - nginx
   - mysql