version: "3.3"
services:
 nginx:
  image: nginx
  ports:
   - "8080:8080"
  links:
   - indexation_1
  volumes: 
   - "./nginx/conf.d/:/etc/nginx/conf.d"
 indexation_1:
  image: pegasusma/indexation:0-SNAPSHOT